# Generated by Django 2.0 on 2017-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171220_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': '该电话号码已存在'}, max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
